apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cptest-app
  namespace: cptest
spec:
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cptest-app 
  targetCPUUtilizationPercentage: 80
