apiVersion: v1
kind: Pod
metadata:
  name: awscli
  namespace: cptest
spec:
  serviceAccountName: cptest-s3-access
  containers:
    - name: awscli
      image: amazon/aws-cli
      command: ["/bin/bash", "-c", "sleep infinity"]
      securityContext:
        privileged: true  # Grants root privileges
        allowPrivilegeEscalation: true  # Allows escalation to root
  restartPolicy: Always

