apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause-pods
  namespace: cptest
spec:
  replicas: 1
  selector:
    matchLabels:
      run: pause-pods
  template:
    metadata:
      labels:
        run: pause-pods
    spec:
      priorityClassName: pause-pods
      containers:
        - name: reserve-resources
          image: registry.k8s.io/pause
          resources:
            requests:
              memory: "3Gi"

