---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cptest-frontend
  namespace: cp-test-app
spec:
  serviceName: "cptest"
  replicas: 1
  selector:
    matchLabels:
      app: cptest
  template:
    metadata:
      labels:
        app: cptest
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: webroot
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: webroot
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ebs-sc
        resources:
          requests:
            storage: 1Gi

