apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-load-generator
  namespace: cptest
  labels:
    app: cpu-load
spec:
  replicas: 30
  selector:
    matchLabels:
      app: cpu-load
  template:
    metadata:
      labels:
        app: cpu-load
    spec:
      containers:
      - name: cpu-load-container
        image: python:3.9
        command: ["python", "-c", "while True: [x**x for x in range(1000000)]"]

