apiVersion: v1
kind: Service
metadata:
  name: svc2-app2
  namespace: cptest2
  labels:
    app: cptest2-dep2-app2
spec:
  selector:
    app: cptest2-dep2-app2  # Matches Pods with the same label
  type: ClusterIP  # Options: ClusterIP, NodePort, LoadBalancer
  ports:
    - protocol: TCP
      port: 80  # Service Port
      targetPort: 80  # Container Port

