apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress
  namespace: cpapp1
spec:
  podSelector: {}
  policyTypes:
    - Egress
    - Ingress
  ingress: []
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
        - ipBlock:
            cidr: ::/0

