apiVersion: v1
kind: Service
metadata:
  name: svc1b
  namespace: cpapp1
  labels:
    app: svc1b
spec:
  selector:
    app: cpapp1b
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

