apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cp-test-app-role-binding
  namespace: cp-test-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cp-test-app-role
subjects:
  - kind: Group
    name: cp-test-app
    apiGroup: rbac.authorization.k8s.io
