apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cp-test-app
  name: cp-test-app-role
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete"]
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]

