apiVersion: v1
kind: Service
metadata:
  name: cptest-app
  namespace: cptest-fargate
  labels:
    app: cptest-app
spec:
  selector:
    app: cptest-app  # Matches Pods with the same label
  type: ClusterIP  # Options: ClusterIP, NodePort, LoadBalancer
  ports:
    - protocol: TCP
      port: 80  # Service Port
      targetPort: 80  # Container Port

