apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-test
  namespace: cptest
spec:
  replicas: 10  # Set a high number of replicas to trigger scaling
  selector:
    matchLabels:
      app: autoscaler-test
  template:
    metadata:
      labels:
        app: autoscaler-test
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sh", "-c", "while true; do echo running; sleep 10; done"]
          resources:
            requests:
              cpu: "500m"  # Request enough CPU to trigger scaling
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

