apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  namespace: cp-test-app
  labels:
    app: ubuntu
spec:
  serviceAccountName: cp-test-app-sa
  containers:
    - name: ubuntu
      image: ubuntu:22.04
      imagePullPolicy: IfNotPresent
      command: ["sleep", "infinity"] # Keeps the container running
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
      volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: db_user
                  name: cp-test-app-creds
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_pass
                  name: cp-test-app-creds
  volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "cp-test-app-creds"
  restartPolicy: Always

