apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: cptest
  labels:
    app: ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu:22.04
      imagePullPolicy: IfNotPresent
      command: ["sleep", "infinity"] # Keeps the container running
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/data"
          readOnly: true
  restartPolicy: Always
  volumes:
    - name: secret-volume
      secret:
        secretName: secret1
        items:
          - key: db_user
            path: DATABASE_USER
          - key: db_pass
            path: DATABASE_PASSWORD
