apiVersion: v1
kind: Pod
metadata:
  name: pod3
  namespace: cptest
  labels:
    app: ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu:22.04
      imagePullPolicy: IfNotPresent
      command: ["sleep", "infinity"] # Keeps the container running
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
      env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: db_user
                  name: secret1
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_pass
                  name: secret1
  restartPolicy: Always

