---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret1
  namespace: cptest
spec:
  encryptedData:
    db_pass: AgCDsqvz2XElkrv8TKcX1sPN3CyrR9u1YlANIdMQiRd5PHx9+uRTA70rGlVcKqw3GbSijrcE17gPUa4QqWILwSie19/ZPiVxbFBsWYLhFcHH+CdV/2zsR7PjednxpgQxzb1PRyYaKvDca09zXMdLCOcQvYeD5J/NRtpf3Ctrl5hyIetWqnCg4Mzd2ksZu5Rhn7LrVIhtYOqJoQWNXEAlmT9jIEtOG/4dkbh21/mpJ8ib1ndelMAA/vWYajFJ1PhzOF2yg8HU9hR9Jx1d6p76lUyehpBrWDwP9GE2vONAzRryWFDZ914kJhAwFQwlKWAo4eUpk1MYTaCQcc97cWs7GsvckPGdb3uDIBIwJGrWPgFoP8fEQS+vS4MBIKxD2R8JiUmyxy29Qoh0Xr5vbUw1LHaNvidztNafzgyOjBfZhKwxPLG/MS16guWH8uNSWqrnGBHepfvj/MrTbBAwPUbZREa/l7T+kF2N/LKuCS1FWln95a9fIe/GcN2Eg1BKrCgIw6z47259T38cC8u5yJs8CrbNBVzddhG2WrqCk5PNdOW2CXKYbWq+J8b4WlVXHVyZ+ujeqbNyxrDj71rOn/h4AcWc4oSV+qmSJnHRWQ2fNcb/ZF3sVBWGoxGhCGG/9WCNWCslHakz6RenURGZcykiUMW44ukLiONKTjuEQZY0Ao+bb6sYQZfQm1TPyITPTdIgCX2WYdQwWY0bEiY7Z3Eko2fQVKes
    db_user: AgBhOJB9Ee6nB4WlrjvcUsaBQyAGDYs/u5VJwBDtcFssYBpUKeg0txm3CU+j0YWb7T83e8NalDV65FWbhlCxfYM1nC9wDJVBVoMF7yl2VzU9JF7kdzahB69e3q6JCDhzYSsDeSoW4dQ9ZCYKidEE9Ro3bSYh/5YIxVrjC2TkUH2dn4XMUPhr9RvuU16LwDFINIUH5WteUg/1CMXecTBCNI24xCFUFClkfAjd3nlTBo1BrcdKgE0/T96ZdPpgd9CmWCah7JMa65/h0XKeR4c3e9uvLlRaDgbtBku28AGknn6tGNKlXyH/CfEQjqZiaDCphNSC2xUpLg1DyOtmBgkPLXrke/KpmvMADNEGMLEzTVEDJHJ3LR+ibS9+a4ttQf8z6tout/ZRZjtt/49UAmJF8ZhrBTfKG6/kxGH/RozhG2iIZolIx5r0Td70kyEbbbPMieWj0X08GavcZyvRAEN2HWVZCgjwr6NazkQkj9mBMhKXWk0DbsltBl4fsrsGEIeXFbVktuy5a0pOKZQy8KgLhPf8N0yuANqF0zdqRPzEnfWn6YSB61zKH3OzoHgmfTtmFecPzNzAdC7JfL1inNpcND600ocUGbekoZRDuzeUHHS3bpEBcpdZOib73ntyqwrnc3BdSWIHa5Vua/Xbc1GUxMWs9sLgx214lffYCgvUhxDcqVk+2BEZMwnSfQApykTP3stJdk3jU4R8mh9OKExNFA==
  template:
    metadata:
      creationTimestamp: null
      name: secret1
      namespace: cptest
    type: Opaque
