apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cp-test-app-creds
  namespace: cp-test-app
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "cp-app-db-creds"
        objectType: "secretsmanager"
        jmesPath:
            - path: db_user
              objectAlias: db_user
            - path: db_pass
              objectAlias: db_pass
    usePodIdentity: "true"
  secretObjects:
    - secretName: cp-test-app-creds
      type: Opaque
      data:
        - objectName: db_user
          key: db_user
        - objectName: db_pass
          key: db_pass

